FROM alpine:latest
ENV DEVOPS="elaktiushin"
EXPOSE 80
RUN apk update && apk upgrade && apk add nginx
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo -e "server {\n    listen 80;\n    server_name dockerhost;\n    location / {\n        root /var/www/;\n        index index.html index.htm;\n    }\n}"> /etc/nginx/http.d/default.conf
CMD ["/bin/sh","-c","echo DEVOPS=$DEVOPS > /var/www/index.html && nginx"]
