use TEST;
CREATE TABLE Students (ID INTEGER PRIMARY KEY, Student TEXT NOT NULL, StudentId INTEGER);
INSERT INTO Students VALUES (1, 'Назар Винник', 1);
INSERT INTO Students VALUES (2, 'Александр Рекун', 2);
INSERT INTO Students VALUES (3, 'Олег Бандрівський', 3);
INSERT INTO Students VALUES (4, 'Владимир Бурдыко', 4);
INSERT INTO Students VALUES (5, 'Вадим Марков', 5);
INSERT INTO Students VALUES (6, 'Игорь Войтух', 7);
INSERT INTO Students VALUES (7, 'Дмитрий Мошна', 8);
INSERT INTO Students VALUES (8, 'Евгений Козловский', 9);
INSERT INTO Students VALUES (9, 'Эд Еленский', 10);
INSERT INTO Students VALUES (10, 'Игорь Зинченко', 11);
INSERT INTO Students VALUES (11, 'Виталий Костюков', 14);
INSERT INTO Students VALUES (12, 'Евгений Лактюшин', 16);
INSERT INTO Students VALUES (13, 'Михаил Лопаев', 18);
INSERT INTO Students VALUES (14, 'Михаил Мостыка', 19;
INSERT INTO Students VALUES (15, 'Андрей Новогродский', 20);
INSERT INTO Students VALUES (16, 'Сазонова Анна', 21);
INSERT INTO Students VALUES (17, 'Дмитрий Соловей', 22);
INSERT INTO Students VALUES (18, 'Артём Фортунатов', 23);
INSERT INTO Students VALUES (19, 'Хоменко Іван', 24);
INSERT INTO Students VALUES (20, 'Алексей Шутов', 26);
INSERT INTO Students VALUES (21, 'Юрий Щербина', 27);
CREATE TABLE Result (ID INTEGER PRIMARY KEY, StudentId INTEGER, Task1 TEXT NOT NULL, Task2 TEXT NOT NULL, Task3 TEXT NOT NULL, Task4 TEXT NOT NULL);
INSERT INTO Result VALUES (1, 1, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (2, 2, 'done+', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (3, 3, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (4, 4, 'done+', 'done+', 'done', 'done');
INSERT INTO Result VALUES (5, 5, 'done', 'done', 'done', 'done');
INSERT INTO Result VALUES (6, 7, 'done+', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (7, 8, 'done', 'not completed', 'done', 'done');
INSERT INTO Result VALUES (8, 9, 'done', 'done+', 'done', 'done');
INSERT INTO Result VALUES (9, 10, 'done+', 'done+', 'done+', 'done');
INSERT INTO Result VALUES (10, 11, 'done', 'done', 'done', 'done');
INSERT INTO Result VALUES (11, 14, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (12, 16, 'done', 'done+', 'done', 'done');
INSERT INTO Result VALUES (13, 18, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (14, 19, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (15, 20, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (16, 21, 'done+', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (17, 22, 'done+', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (18, 23, 'done', 'done', 'done+', 'done+');
INSERT INTO Result VALUES (19, 24, 'done', 'done', 'done', 'done');
INSERT INTO Result VALUES (20, 26, 'done', 'done+', 'done+', 'done+');
INSERT INTO Result VALUES (21, 27, 'done+', 'done+', 'done+', 'done+');