FROM alpine:latest
ENV DEVOPS="elaktiushin"
EXPOSE 80
RUN apk update && apk upgrade && apk add nginx
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN mkdir -p /usr/share/nginx/html
COPY ./default.conf /etc/nginx/http.d/default.conf
RUN echo "DEVOPS=$DEVOPS" > /usr/share/nginx/html/index.html
CMD [ "nginx" ] 
